# Generated by Django 2.2 on 2019-10-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('ack_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
