# Generated by Django 2.2 on 2019-10-27 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_report', '0005_auto_20191027_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_clean_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ack_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart_report.RawData')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smart_report.RawData')),
            ],
        ),
    ]
